### ISSUE TITLE
Create a README.md for the sample app

### ISSUE THREAD

**Issue by yamboy1** [alallier/reload#124]
It might be a good idea to create a readme file for the [expressSampleApp](../tree/master/expressSampleApp). People might open the sample app and have no idea how to use it.

@alallier What are your thoughts on creating this?

**Comment by alallier** [comment]
Yep it a great idea, this is what I had planned for #45. Since this is a duplicate of that really I'm going to close this.

**Comment by alallier** [comment]
Feel free to mention this in a comment on #45 though so it is clear
