### ISSUE TITLE
Reload command line only serves HTML files

### ISSUE THREAD

**Issue by alallier** [alallier/reload#133]
The [latest reload command line work](https://github.com/alallier/reload/pull/132) caused a regression only causing HTML files to be served.

**Comment by alallier** [comment]
I have a solution made for this, just have to finish testing and correct later today, when I have more time.

**Comment by AckerApple** [comment]
I recommend not being a hero and opt to using a dependency to serve static files. There is so so much I believe you are under esitimating here.

I'll be happy to ride your coat tails the whole way though. You've haphazardly released this code, dismissed my code (cause you don't have time for time saving code), and are willing to implement delay timers like it's the 90s, has made following this package a thing of entertainment from me.

Keep it up

**Comment by bcherny** [comment]
@alallier Any updates, or maybe a revert? The CLI is unusable as-is.

**Comment by alallier** [comment]
Yes have a fix waiting in #134. Will get that in tonight for you

**Comment by alallier** [comment]
@bcherny Should be good now. If you have any other further issues please file an issue.
