### ISSUE TITLE
The client has been asking reload.js for 400 errors, and the update browser is invalid

### ISSUE THREAD

**Issue by geekwill** [alallier/reload#136]
The client has been asking reload.js for 400 errors, and the update browser is invalid

**Comment by alallier** [comment]
Can you provide some more details here. Can you provide your setup, show some screenshots etc.?

**Comment by AckerApple** [comment]
May I recommend you uninstall reload and then reinstall with the following command:

```bash
npm install -g reload@2.0.1
```

I am suspicious of the current release 2.2.0

**Comment by alallier** [comment]
Like @AckerApple mentioned `2.2.0` is broken right now but **only** for command line usage. If you are using reload in Express it should be fine. Let me know what you are using and we can figure this out.

**Comment by alallier** [comment]
It has been a month since a reply on this issue. I'm going to close this issue. If feedback is provided and it is still a problem I'd be happy to reopen it.
