### ISSUE TITLE
Cannot serve static file anymore since 2.2.1

### ISSUE THREAD

**Issue by roben** [alallier/reload#138]
I have the following script in my package.json:

`"reload": "reload --verbose -b -p 12080 -d /tmp/mytestdir"`

In `/tmp/mytestdir` there is one static `index.html` file (and two leftover `index.pdf` and `output.pdf`). With `2.2.0` everything works as expected: When `index.html` is updated, it is automatically reloaded in the browser. Since `2.2.1`, though, only `File Not Found` is shown. Touching/changing the `index.html` file has no effect. Reverting back to `2.2.0` fixes this for me.

**Comment by alallier** [comment]
It's possible something is going on with the directory argument. I'll test later and see if I can reproduce.

**Comment by roben** [comment]
Thanks. If it is in fact the argument parsing: I changed the directory name for this issue report, the real one has a "-" in it, as in `my-testdir`.

**Comment by AckerApple** [comment]
In the meantime, this fork of reload, works great and better for several reasons: https://www.npmjs.com/package/ack-reload#benefits-of-ack-reload-over-original-reload-package

Give it try

**Comment by alallier** [comment]
@roben I was able to recreate the problem and have provided a fix in #139. If you have a chance can you test for me to see if it solves your problem (it should). I'll give you a bit to try it out, if not I'll probably merge it in a day or so.

**Comment by alallier** [comment]
I just published the latest (2.2.2), let me know if you still have any problems after this fix.

**Comment by roben** [comment]
Sorry, I did not have time to try it out until now. 2.2.2 works just fine, thanks!
