### ISSUE TITLE
Doesn't work in latest Firefox

### ISSUE THREAD

**Issue by davidhq** [alallier/reload#144]
I tried `reload -b`, worked in chrome (site reloaded if I edited index.html), Firefox (Quantum) didn't reload...

I could also investigate in the future because this npm package seems great and useful but if you suspect what could be wrong already, please fix :)

**Comment by alallier** [comment]
I just tested in the latest Firefox and it is working for me. Can you provide output from the Firefox console?

**Comment by davidhq** [comment]
Somehow it works for me this time as well... maybe I did something wrong earlier. Sorry and thank you for now.

**Comment by alallier** [comment]
Yep no problem happy to help.
