### ISSUE TITLE
Feature Request: CLI "Pre-Processing" and "Post-Processing"

### ISSUE THREAD

**Issue by FireController1847** [alallier/reload#150]
Similar to how [node-sass-watcher](https://github.com/kottenator/node-sass-watcher) works, it'd be awesome if we had the ability to specify commands before and after the page is reloaded. For example, I could do something like this:
```json
"scripts": {
  "watch": "reload -b -d ./src -pre 'npm run build:scss'",
  "build:scss": "node-sass -r ./src/scss/ -o ./src/css/ --output-style expanded"
}
```
This would allow me to be able to run my build scripts and then reload the page. It'd be very similar to how webpack's --watch function works. It will build, then reload! It'd be awesome if this could be an ability!

**Comment by alallier** [comment]
My hunch is this is out of the scope of reload. The command line tool is really suppose to be a nice dev tool while working on some static HTML. It seems you want to use reload to be the server to a more complex web application. If you want to use reload in that more complex case you should be using the express version of reload and use a server or some other workflow to act as the server to host your application.

I am going to close this for now but I am happy to continue the conversation here for now. If for some reason the conversation leads to a good argument to why this should be supported I will re-open the issue

**Comment by FireController1847** [comment]
I don't even remember what I was trying to use this for haha

**Comment by alallier** [comment]
My apologies I didnt triage this in a timely matter
