### ISSUE TITLE
Still reloads for non '-e' extensions

### ISSUE THREAD

**Issue by FireController1847** [alallier/reload#151]
I'm not sure if I'm understanding the `-e` option right, but here's what I'm running.
```bash
reload -b -d ./src -e html,js,css
```
While only `html`, `js`, and `css` are marked, `.scss` and `.txt` files still cause the browser to reload.

**Comment by alallier** [comment]
Unable to replicate. Are you able to provide a sample repository?

**Comment by FireController1847** [comment]
Man I don't even know if I still have that repository anymore, it's been such a long time. Sorry about this!

**Comment by alallier** [comment]
Again sorry for a non timely triage on this

**Comment by FireController1847** [comment]
Not a problem, it's okay
