### ISSUE TITLE
Express Example does'nt work

### ISSUE THREAD

**Issue by alfenfebral** [alallier/reload#162]
Already insert
<script src="/reload/reload.js"></script>
to index.html
and 
reload(app)

but does'nt work ?

**Comment by alallier** [comment]
Can you please provide an example that I can replicate? For example seeing your full HTML and JS file that is requiring reload would help

**Comment by glee2017** [comment]
I ran into the same issue and above suggestion worked for me. 

here are my updates to express-generator code, hope this helps: 

**app.js:** 
var reload = require('reload');   //added under var logger = required('morgan')
reload(app) -// added directly under app.use('/users', usersRouter); as suggested above.

**layout.twig:**
<script src="/reload/reload.js"></script>

Thanks!

**Comment by alallier** [comment]
I just tested the sample app and it is working as intended. I think the completion of #45 will help with issues like this.

Happy to continue discussion on this issue and/or re-open as necessary
