### ISSUE TITLE
Cannot find module '../../reload'

### ISSUE THREAD

**Issue by Emmanuel974** [alallier/reload#163]
Hi, we have this issue with reload:
Cannot find module '../../reload'

What wrong ?
 best regard

**Comment by alallier** [comment]
@Emmanuel974 please provide a minimum example so I can help you debug your error.

**Comment by Emmanuel974** [comment]
`const express = require ('express');
const path = require('path');
const app = express();
const reload = require ('../../reload');


//Getting our PECHES routes

const routes = require('./server/routes/routes');

app.use(express.static(path.join(__dirname, 'dist/ang-node')));
app.use('/routes', routes);

//Catch all other routes request and reurn ot to the index

app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'dist/ang-node/index.html'))
});

const forceSSL = function() {
    return function (req, res, next) {
      if (req.headers['x-forwarded-proto'] !== 'https') {
        return res.redirect(
         ['https://', req.get('Host'), req.url].join('')
        );
      }
      next();
    }
  }
  // Instruct the app
  // to use the forceSSL
  // middleware
  app.use(forceSSL());




const port = process.env.PORT || 8080;

reload(app);

app.listen(port, (req, res) => {
    console.log('RUNNING on port' + " " + port);
});`

**Comment by alallier** [comment]
Do you have an installed copy of reload two directories up? Typically if you installed this with a `package.json` you would require it like `require('reload');`

**Comment by dlepaux** [comment]
Hello @Emmanuel974 
You have just to do npm i reload in the example... 
Hello @alallier 
I think that to provide a better user/developer experience, you can use your npm package instead of your local one ? By changing the `require(../../reload)` to `require('reload')`
After doing that I change code in the html or server.js and nothing happen.
It's very frustrating....

**Comment by alallier** [comment]
I don't believe there is a bug in reload here just a application specific configuration problem. Closing for now. Happy to help you both further is this issue as necessary
