### ISSUE TITLE
urls must explicitly end with .html in order to work

### ISSUE THREAD

**Issue by AlexanderSopov** [alallier/reload#166]
When running reload on OSX, I can't find how to serve html-files without needing to explicitly end each url (except for home page) with .html.

For example:
`localhost:8080/` works fine and serves index.html, but `localhost:8080/about-us ` doesn't work and gives me a "Cannot GET /about-us"-message. However, `localhost:8080/about-us.html ` works fine.

Is there a fix for this?

**Comment by alallier** [comment]
Thanks for the filling the issue, I believe I have someone who will take care of this. If not I will work on this for you.

**Comment by alallier** [comment]
Closed by #167
