### ISSUE TITLE
Update README and Express Sample App to show promise return API. The manual reload README example also needs updating.

### ISSUE THREAD

**Issue by cekvenich** [alallier/reload#180]
Manually firing server-side reload events no longer works w/ v3.
    reloadServer.reload() now says no such function.

I'm reverting to old version for now.

**Comment by alallier** [comment]
I apologize about that! The unit tests _should_ have caught this but I will look into this as soon as I can for you

**Comment by alallier** [comment]
@cekvenich can you provide more information or an example repository. I am unable to reproduce.

**Comment by cekvenich** [comment]
https://github.com/metabake/mbake/blob/master/src/lib/Wa.ts

Line 136 under 2.4 works in 3 it says method not found.

**Comment by alallier** [comment]
Reload returns a promise now in v3 so you will have to make sure you are handling the asynchronous properties of it properly. Please consult the [Migration Guide](https://github.com/alallier/reload/blob/master/MIGRATION_GUIDE.md#version-2x---3x). Give that a look and let me know if you need further help.

**Comment by cekvenich** [comment]
I think I know promises and I did see that - I assumed the second one is a promise. 
But now I guess it is the first reload that is the promise. Will try.

**Comment by cekvenich** [comment]
It would help if the readme on this topic was corrected to show what promise returns. The server?

**Comment by alallier** [comment]
Yeah @cekvenich you are correct I need to update the documentation to be correct, I will do that. The promise returns the object documented [here](https://github.com/alallier/reload#returns)

**Comment by alallier** [comment]
Modifying the sample app slightly this would do what you want

```js
reload(app).then(function (reloadReturned) {
  reloadReturned.reload()
}).catch(function (err) {
  console.error('Reload could not start, could not start server/sample app', err)
})
```

**Comment by karlitos** [comment]
This worked for me:
```javascript
reload(app).then((reloadReturned) => {
    // do some adidional steps like app.listen(...)
    watch.watchTree(__dirname + "/public", function (f, curr, prev) {
        // Fire server-side reload event
        reloadReturned.reload();
     })
}).catch(function (err) {
    console.error('Reload could not start, could not start server/sample app', err)
})
```

also possible

```javascript
let reloadServer;
reload(app).then((reloadReturned) => {
    reloadServer = reloadReturned;
    // do some adidional steps like app.listen(...)
}).catch(function (err) {
    console.error('Reload could not start, could not start server/sample app', err)
})

watch.watchTree(__dirname + "/public", function (f, curr, prev) {
    // Fire server-side reload event when server initialised
    if (reloadReturned) reloadReturned.reload();
})
```

With `async/await` is it even simpler:
```javascript
const startServer = async () => {
    const reloadServer = await reload(app);
    // do some adidional steps like app.listen(...)
    watch.watchTree(__dirname + "/public", function (f, curr, prev) {
        // Fire server-side reload event
        reloadServer.reload();
    })
}
```
