### ISSUE TITLE
Docker usage

### ISSUE THREAD

**Issue by ivorcummings** [alallier/reload#202]
Any tips on how to get reload in a docker container refreshing my host machine browser?
Should I be exposing a specific port or something?

**Comment by ivorcummings** [comment]
Answered my own question. Needed to open up port 9856 on the host and in the container.

**Comment by alallier** [comment]
Perfect, yes that is correct! Sorry I didn't get to this before you. The port is also [configurable](https://github.com/alallier/reload#table-of-options-for-reload-opts-parameter) if you do want to change it.
