### ISSUE TITLE
Can HTTPS be used from the command line?

### ISSUE THREAD

**Issue by SeanBannister** [alallier/reload#281]
I use reload on the command line and need to serve using HTTPS, this doesn't appear to be possible? Could someone please confirm if I've missed something,

**Comment by alallier** [comment]
It is not currently supported. Reload command line is intended as dev tool.

What the use case?

**Comment by SeanBannister** [comment]
The new javascript [File System Access API](hhttps://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) won't work unless its served over HTTPs. 

I often develop small projects without any build tool and just use reload to view the project as some JS features won't work if served from file:// and apparently now some don't work if served over http://

**Comment by alallier** [comment]
I'm hesitant to add this due to complexity but I suppose in your use case I could see how this needed/helpful. Reload does support HTTPS for express so we could feather the HTTPS support into the command line side of things

PRs welcome

**Comment by alallier** [comment]
After some consideration I don't want to support HTTPs on the command line since it would create unneeded complexity as Reload command line is designed to be a development tool.

**Comment by SeanBannister** [comment]
Just note that this means reload cannot be used as a development tool if you're using the [following Javascript APIs](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts) which require HTTPs:

- [Async Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard)
- [Audio Output Devices API](https://developer.mozilla.org/en-US/docs/Web/API/Audio_Output_Devices_API)
- [Background Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API)
- [Background Synchronization API](https://developer.mozilla.org/en-US/docs/Web/API/Background_Synchronization_API)
- [Badging API](https://developer.mozilla.org/en-US/docs/Web/API/Badging_API)
- [Barcode Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API)
- [Battery Status API](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API)
- [Cache-Control: immutable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control)
- [Contact Picker API](https://developer.mozilla.org/en-US/docs/Web/API/Contact_Picker_API)
- [Content Index API](https://developer.mozilla.org/en-US/docs/Web/API/Content_Index_API)
- [Cookie Store API](https://developer.mozilla.org/en-US/docs/Web/API/Cookie_Store_API)
- [Credential Management API](https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API)
- [Device Memory API](https://developer.mozilla.org/en-US/docs/Web/API/Device_Memory_API)
- [Device Orientation / Device Motion](https://developer.mozilla.org/en-US/docs/Web/API/Device_orientation_events/Detecting_device_orientation)
- [Document Picture-in-Picture API](https://developer.mozilla.org/en-US/docs/Web/API/Document_Picture-in-Picture_API)
- [EyeDropper API](https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper)
- [Encrypted Media Extensions](https://developer.mozilla.org/en-US/docs/Web/API/Encrypted_Media_Extensions_API)
- [File System API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API)
- [Generic Sensor API](https://w3c.github.io/sensors/)
- [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API)
- [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)
- [Idle Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Idle_Detection_API)
- [Keyboard API](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard_API)
- [Local Font Access API](https://developer.mozilla.org/en-US/docs/Web/API/Local_Font_Access_API)
- [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API)
- [Payment Handler API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Handler_API)
- [Payment Request API](https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API)
- [Presentation API](https://developer.mozilla.org/en-US/docs/Web/API/Presentation_API)
- [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API)
- [Reporting API](https://developer.mozilla.org/en-US/docs/Web/API/Reporting_API)
- [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API)
- [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API)
- [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)
- [Shared Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Shared_Storage_API)
- [Storage API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API)
- [VirtualKeyboard API](https://developer.mozilla.org/en-US/docs/Web/API/VirtualKeyboard_API)
- [Web Authentication API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)
- [Web Bluetooth](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API)
- [Web Locks API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API)
- [Web MIDI](https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API)
- [Web NFC API](https://developer.mozilla.org/en-US/docs/Web/API/Web_NFC_API)
- [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API)
- [WebCodecs API](https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API)
- [WebGPU API](https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API)
- [WebHID API](https://developer.mozilla.org/en-US/docs/Web/API/WebHID_API)
- [WebOTP API](https://developer.mozilla.org/en-US/docs/Web/API/WebOTP_API)
- [WebTransport API](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport_API)
- [WebUSB API](https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API)
- [WebXR Device API](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API)
- [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API)
- [Window Management API](https://developer.mozilla.org/en-US/docs/Web/API/Window_Management_API)
