### ISSUE TITLE
Refused to connect to 'ws://localhost:9856/'

### ISSUE THREAD

**Issue by vrg-success** [alallier/reload#285]
I started server on 8080 port and on any page I got the error in console google-chrome:

reload.js:96 Refused to connect to 'ws://localhost:9856/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by alallier** [comment]
I just tested the [sample app](https://github.com/alallier/reload-sample-app) with version 89.0.4389.114 of Chrome. Can you provide a sample app/sample HTML and where/how you are using reload in more detail?

**Comment by alallier** [comment]
Closing due to no feedback, happy to re-open with more information
