### ISSUE TITLE
Why is it so slow?

### ISSUE THREAD

**Issue by Hubro** [alallier/reload#308]
I wanted to use this plugin to instantly display changes in a browser window as I worked on a HTML file. However, every time I press save, it takes 1-2 seconds before the browser window reloads. Why is it not instant? Is there a built-in debounce function or scan interval that I can configure somehow?

**Comment by alallier** [comment]
Can you provide some more details on how you are using Reload?

It sounds like you are using the command line capability to Reload. I personally don't see any delay. If you can provide some more details or reproduction steps, I'd be happy to help you out.

**Comment by Hubro** [comment]
I'm just doing:

```
$ reload -d public/
```

If I start it with `-v` then I see it says "Starting WebSocket Server" around 1 seconds after I save a file, then the browser is reloaded around 0.5 seconds after that.

**Comment by Hubro** [comment]
```
$ inotifywait -m public/index.html
Setting up watches.
Watches established.
public/index.html MOVE_SELF
public/index.html ATTRIB
public/index.html DELETE_SELF
```

I'm using Neovim, and apparently it saves file by moving them, deleting them then creating a new file :thinking: 

Could that negatively affect reload?

**Comment by Hubro** [comment]
Nope, this is not the cause. I just tested with:

```
$ echo TESTESTESTEST >> public/index.html
```

And it still takes a couple of seconds for the change to show up in the browser.

**Comment by alallier** [comment]
Personally I would say a second or two for the browser to refresh isn't a bug. Obviously it feeling "slow" is objective. It's pretty instant on my machine. If reload was taking many seconds to refresh I would say we have something to look into.

I'm going to close this for now but if you have a sample app available or more information to suggest a significant delay. I'm happy to re-open this and debug further

**Comment by Hubro** [comment]
I couldn't disagree more. There is no reason it should take any longer than a few milliseconds for the browser to start reloading. The browser should start reloading before you can even release the save key. We're talking about fast flash storage (probably cached in RAM) and local network traffic. In this context, I would say that taking 1-2 *thousand* milliseconds to even *start* reloading the webpage is **glacially** slow, and for me it feels extremely unresponsive.

But if this delay is considered acceptable for this project, that's fine, I will just find another solution.

**Comment by markcellus** [comment]
@Hubro experiencing the same thing. Did you ever find a faster solution?

**Comment by markcellus** [comment]
Actually, I just tried using the package programmatically (using [this example](https://github.com/alallier/reload/tree/5b32e88449482a44b6b0426b6e81979a76e6c1bc#manual-fire-with-promises)), swapped out [`watch`](https://www.npmjs.com/package/watch) package with [`chokidar`](https://www.npmjs.com/package/chokidar) and it works much faster!
