### ISSUE TITLE
options are lost in reloadReturned with 3.x

### ISSUE THREAD

**Issue by pcnate** [alallier/reload#311]
Upon upgrading from reload@2.3.1 to 3.2.x I have discovered that the following values are not verifiable on the output;

```js
const express    = require('express');
const http       = require('http');
const reload     = require('reload');
const portfinder = require('portfinder');

const app        = express();
const server     = http.Server( app );

portfinder.getPort( async ( err, port ) => {

  server.listen( port, async () => {
    let address = server.address();
    console.log( `server listening via ${ address.family } on ${ address.address }:${ address.port }` );

    let reloadPort = port + 1;
    let options = { port: reloadPort }

    let output = await reload( app, options );
    console.info( `reloadjs listening on port: ${ output?.wss?.options?.port }`, reloadPort )
    console.log( output )
  });

});
```

Using "reload": "^3.2.0"
![image](https://user-images.githubusercontent.com/621940/142514929-36ef3b18-11f1-4003-93c9-9fb45677ad69.png)

Using "reload": "2.3.x"
![image](https://user-images.githubusercontent.com/621940/142515023-b182991b-2d2b-45be-9992-8161a0927a61.png)

Using
 * NodeJS v14.17.5
 * npm v8.1.3
 * Windows 10 Pro 21H1 19043.1348

**Comment by alallier** [comment]
Yes @pcnate you have it correct it's due to the `ws` update. We are simply returning the `wss` object wholesale.
