### ISSUE TITLE
Stop trying to refresh

### ISSUE THREAD

**Issue by tik9** [alallier/reload#312]
How can I stop the refresh if nodemon is not connected any more. My Workaround now is close the browser tab or refresh the tab - but is there a programmatic way to stop the polling?
I use the [express mode](https://github.com/alallier/reload#express-example)
It always tries to refresh and brings the following websocket connection error because there is no server live:
`reload.js:96 WebSocket connection to 'ws://localhost:9856/' failed:`

**Comment by alallier** [comment]
This cannot be suppressed this is because this is how Reload fundamentally works. It creates a websocket server and the client watches for that socket liveliness to determine when to reload.
