### ISSUE TITLE
Need Unit Tests

### ISSUE THREAD

**Issue by alallier** [alallier/reload#42]

**Comment by AckerApple** [comment]
My pull request addresses this by adding the mocha testing environment. Please review my pull request: https://github.com/jprichardson/reload/pull/62

**Comment by yamboy1** [comment]
@alallier What tests do you want to run?

**Comment by alallier** [comment]
Sorry I meant to assign this to myself, as I have already started working on this. I want to test everything naturally. Once I get the first iteration up and merged you can step it and follow my lead if you want to help.

**Comment by AckerApple** [comment]
May I please recommend that you do not involve Express in starting up a server to test against. Especially that being one of the items ya'll are addressing in removing Express
