### ISSUE TITLE
Add a how to contribute section to README

### ISSUE THREAD

**Issue by alallier** [alallier/reload#51]
It would be useful to have a how to contribute section in the README that could outline, our coding conventions, to run `npm test`, etc.

**Comment by yamboy1** [comment]
@alallier I think that it would be better to create a CONTRIBUTING.md which will appear automatically whenever someone opens a pull request or issue. We could have a link to the CONTRIBUTING.md from README.md

**Comment by alallier** [comment]
I have a specific idea in mind for a CONTRIBUTING.md document that is separate from this, I will file later and link to this issue.
