### ISSUE TITLE
Make so reload cmd line supports query string

### ISSUE THREAD

**Issue by cdiddy77** [alallier/reload#55]
when I run the command line reload:
If, in a browser, I attempt to navigate to a URL with a query string, the load fails. Reload reports:
Error: ENOENT: no such file or directory, open '<path to my filename>?query=string

It would be pretty trivial to parse off the query string before looking for the filename.

**Comment by yamboy1** [comment]
Could you explain exactly what you did, so I can reproduce it.

**Comment by alallier** [comment]
Can you provide more details on this? I just ran a test of mine and couldn't seem to replicate the issue

**Comment by alallier** [comment]
Going to close for now as it seems @yamboy1 and myself could not replicate the issue. If this is still a problem please reopen with further instructions on how to reproduce the bug
