### ISSUE TITLE
"reload..." message should have a timestamp

### ISSUE THREAD

**Issue by jprichardson** [alallier/reload#7]

**Comment by alallier** [comment]
Would something like this be alright

```
restarting...
restarted January 26th 2016, 4:06:11 pm
```

**Comment by jprichardson** [comment]
Sure. You could even be more succinct if you like. Also the `restarting...` line probably wouldn't be necessary anymore. Your call though on all of it.

**Comment by yamboy1** [comment]
I've made a pull request for it here #72. I know there are a lot of commits, but the end result works. Also it updates standard to 10.0.2 which was necessary for the build to pass on nodejs 0.1 and 0.12.

**Comment by yamboy1** [comment]
@alallier You should probably close this issue now

**Comment by alallier** [comment]
I will close when the feature branch makes it into master

**Comment by yamboy1** [comment]
So when you merge v2.0.0 into master?

**Comment by alallier** [comment]
Correct
