### ISSUE TITLE
Listen to events/ reload callback

### ISSUE THREAD

**Issue by IamCarbonMan** [alallier/reload#93]
It would be useful to pass reload a callback to run each on each reload.

**Comment by alallier** [comment]
I like the idea, not sure if it should live in reload though. Can you explain your use case more?

**Comment by yamboy1** [comment]
@alallier What are we going to do about this issue?

**Comment by IamCarbonMan** [comment]
@alallier At the time I was using this, I was working on doing some human processing of a very large folder of images. The server would serve up each image along with a list of distinct colors found in that image (using imagemagick) and the client would respond with the user's choice of colors to replace. (For example if an image contained red, gold and lilac, the user might decide to replace

**Comment by AckerApple** [comment]
In my fork of reload, [ack-reload](https://www.npmjs.com/package/ack-reload), I added onReload

The code, as seen here, uses the universal web socket client reload function to fire options.onReload:
https://github.com/AckerApple/reload/blob/master/lib/reload.js#L177

The readme for my onReload and other arguments
https://www.npmjs.com/package/ack-reload#arguments

**Comment by alallier** [comment]
Going to close, this needs more information. Happy to re-open if we can get some substance here
