### ISSUE TITLE
can't find reload.js

### ISSUE THREAD

**Issue by 39Er** [alallier/reload#95]
server
```
const reload = require('reload');
  const http = require('http');

  const server = http.createServer(app);
  require('./client/router/routes')(app);
  reload(server, app);
  server.listen(port, () => {
    logger.info('App (dev) is now running on %s', port);
  });
```
index.html
`<script src="/reload/reload.js"></script>`

routes.js

```
module.exports = function (app) {
  app.get('/*', (req, res) => {
    res.render('index');
  });
};

```
Those are my codes.But it can't find reload.js.
I think it because I use '/\*' to render html.Dose reload use '/reload' route? My app is a SPA,so I must use '/\*',how can I solve that? By the way,I think using '/reload' route to reload is not a good idea,because it's invasive.Can you give me some advice?

**Comment by yamboy1** [comment]
Could you post the exact error please.

**Comment by alallier** [comment]
Yes reload creates a [`/reload` route](https://github.com/jprichardson/reload/blob/master/lib/reload.js#L28).

**Comment by 39Er** [comment]
@alallier  So how can I desgin the '/reload ' route to reload my page ?

**Comment by alallier** [comment]
@39Er just make sure you load reload before your `/*` route. That way your application can still hit the reload route. Express route order matters.
